# In this notebook we'are going to cover some of the most fundametal concepts of tensor using TensorFlow 



## Introduction yo Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# Create tensor with tf.constant()
scalar=tf.constant(7)#Bu kod, TensorFlow'da bir sabit tensör oluşturur ve değeri 7 olarak ayarlar. Bu tensör bir skalerdir, yani bir sayısal değerdir.
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (Tensor'ün boyut sayısını kontrol etmek)
scalar.ndim

0

In [4]:
# Create a vector (Vektör oluşturma)
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector(Vektörümüzün boyutuu kontrol etmmek)
vector.ndim

1

In [6]:
# Create a matrix (Matrix yaratmak bir matrixin birden fala boyutu vardır)
matrix=tf.constant([[10,7],
                    [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix(Başka bir metrix yaratma)
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16)# float 16 veri tipindenden olan bir matrix yarattık 3 satir ve 2 sutundan olusan
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# what's the number dimensions of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor (Bir tensor oluşturalım)
tensor=tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                     [10,11,12]],
                     [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far(Şimdiye kadar ne yarattık)
* Scaler: a single number
* Vector: a number with direction
* Matrix: a 2 dimensional array of numbers(Matrix 2 boyutlu saylardır)
* Tensor: an n-dimensionel array of numbers (Tensor ise n boyutlu sayılardan oluşur n herhangi bir sayı olabilir 0 da 1000 de olabilir)

### Creating tensors with 'tf.Variable'

In [12]:
# Create the same tensor with tf.Variable() as above
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try change one of the elements in our changeable tensor (tensor'larımızdaki unsurlardan birini değiştirmeyi deniyelim)
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [15]:
# Let's try change our unchangable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

### Creating random tensors
Raandom tesnors are tensores of same abitrary size random numbers(Yeni rasgele tensorler rasgele sayılar içeren bazı keyfi boyutlardaki zamanlardır)

In [ ]:
# create two random (but the same) tensors
random_1=tf.random.Generator.from_seed(7)
random_1=random_1.normal(shape=(3,2))
#Bu kod, TensorFlow kütüphanesinin random modülünü kullanarak, normal dağılıma göre rastgele sayılar üretir.

#İlk satırda, rastgele sayıların üretiminde kullanılacak olan random_1 adlı bir nesne oluşturulur ve 42 sayısı ile başlatılır. Bu nesne, TensorFlow'un random modülünden türetilmiştir.

#İkinci satırda, normal() metodu kullanılarak, random_1 nesnesinden 3 satır ve 2 sütundan oluşan bir dizi üretilir. Bu dizi, normal dağılıma göre rastgele sayılar içerir. Bu sayılar, her seferinde farklı olacaktır, ancak 42 başlangıç değeri sabit kalacaktır.

#Sonuç olarak, random_1 adlı değişkende 3 satır ve 2 sütundan oluşan bir dizi saklanacaktır, ve bu dizi normal dağılıma göre rastgele sayılar içerecektir.
random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))

# Are they equal?
random_1,random_2,random_1==random_2

#### Shuffle the order of elements in a tensor(Bir tensördeki elemanları karıştırmak)

In [16]:
# Shuffle a tesnor(valuable for when you want to shuffle your data so the inherent order doesn't effect learning )
not_shuffled=tf.constant([[10,7],
                          [3,4],
                          [2,5]])
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [17]:
# shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#### Exercise

In [19]:
shuffled_new=tf.constant([[1,2],
                          [3,4],
                          [4,5]])
tf.random.shuffle(shuffled_new)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [3, 4]], dtype=int32)>

In [20]:
shuffled_new1=tf.constant([[90,100],
                           [40,80],
                           [70,50]])
tf.random.shuffle(shuffled_new1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 40,  80],
       [ 70,  50],
       [ 90, 100]], dtype=int32)>

In [21]:
# shuffle our non-shuffled tensor
tf.random.set_seed((42))
tf.random.shuffle(shuffled_new1,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 90, 100],
       [ 40,  80],
       [ 70,  50]], dtype=int32)>

In [22]:
tf.random.set_seed(42)# global level random seed
tf.random.shuffle(not_shuffled,seed=42)# operation level random seed
## sürekli aynı sırada karıştırmak istiyorsak tensor'leri seed kullanırız

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#### Other ways to make tensors (tensors yapmanın başka yolları)

In [23]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [24]:
# Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [25]:
# Numpy arraylerini tensore çevirebiliriz
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [26]:
A=tf.constant(numpy_A,shape=(3,8))# numpy arrayini tensor'e çevirdik 2 3 4 çarpılmları eleman sayısına eşit olmalıdır yani 24'e 
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [27]:
A.ndim

2

### Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [28]:
# Create a rank 4 tenor(4 dimensions)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [29]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
2 * 3 * 4 * 5

120

In [31]:
print('Datatype of every element:',rank_4_tensor.dtype)
print('Number of dimensions (rank):',rank_4_tensor.ndim)
print('Shape of tensor:',rank_4_tensor.shape)
print('Elements along the 0 axis:',rank_4_tensor.shape[0])
print('elemetns along the last axis',rank_4_tensor.shape[-1])
print('Total number of elements in our tensor:',tf.size(rank_4_tensor))
print('Total number of elements in our tensors',tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
elemetns along the last axis 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensors 120


### Indexing tensors

In [32]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [33]:
# Get the first elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [34]:
some_list[:1]

[1]

In [35]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [36]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [38]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [39]:
some_list,some_list[-1]

([1, 2, 3, 4], 4)

In [40]:
# Get the last item of each  row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [41]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
# Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor,axis=-1)# son eksende genişletecek expand genişletmek anlamna gelir '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [43]:
# Expend 0-axis
tf.expand_dims(rank_2_tensor,axis=0)# sıfır ekseninde genişletme expend the 0 axis yani 1 boyut eklemiş oldu başa

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [44]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

#### Manipulating tensors (tensor oprerations)
**Basic operations**

'+','-','*','/'

In [45]:
# You can add values to a tensor using the addition operator
tensor=tf.constant([[10,7],
                    [3,4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [46]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [47]:
# Multiplacation also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [48]:
# Subsraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [49]:
# We can use the tensorflow bult-in fucntion too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [50]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplacation**(Matrix çarpımları)

# Matrix multiplication in tenserflow

In [51]:
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [52]:
tensor,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [53]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [54]:
# Matrix multliplication with Python aperator '@' pythonda matrix çarpımı yapmak için @ operatörünü kulanıyoruz
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [55]:
tensor.shape

TensorShape([2, 2])

In [56]:
# Create a tensor (3,2) tensor 
X=tf.constant([[1,2],
               [3,4],
               [5,6]])
# Create another (3,2) tensor 
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [57]:
# Tyr to matrix multiply tensors of same shape (Aynı şekildeki matrixleri çarpma) 
X @ Y

InvalidArgumentError: ignored

In [58]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [59]:
# Let's change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [60]:
X.shape,tf.reshape(Y,shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [61]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
tf.reshape(X,shape=(2,3)).shape,Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [64]:
# Try change the shape of X instead of Y
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [65]:
# Can do the same with transpose(transpoz işlemi ile yeniden şekilendirme)
X,tf.transpose(X),tf.reshape(X,shape=(2,3))
#tf.transpose(X) işlemi matrisin satır ve sütunlarını yer değiştirir. Bu işlem sonucunda, matrisin transpozesi elde edilir.

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [66]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**

Matrix çarpım olarak adlandırılır

You can perform matrix multiplication using:

* tf.matmul()

* tf.tensordot(),

* @

In [67]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [68]:
# Perfrom the dot product on X  and Y (requires X or Y to be be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)
# Burada, axes=1 parametresi, A ve B tensörlerinin sütunları ile satırları arasında bir eşleştirme yapılacağını belirtir. C tensörü, A ve B tensörlerinin nokta çarpımını temsil eder.

# Bu şekilde, tf.matmul() fonksiyonu matrisler arasındaki doğrudan bir çarpma işlemi gerçekleştirirken, tf.tensordot() fonksiyonu nokta çarpımı yapmak için iki tensörün şekillerini eşleştirir.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [69]:
# Perform matrix mutliplication between X and Y (transposed)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [70]:
# Perform matrix mutliplication between X and Y (reshaped)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

transpose işlemi ise, tensörün boyutlarını yer değiştirir. Matrislerde transpoze, matrisin satır ve sütunlarının yer değiştirmesi anlamına gelir. transpose işlemi, tensörün elemanlarının dizilimini değiştirmez, ancak tensörün şeklini değiştirir.

Bu nedenle, reshape ve transpose işlemleri farklı sonuçlar verirler ve farklı amaçlar için kullanılırlar. reshape işlemi tensörün şeklini değiştirirken, transpose işlemi tensörün boyutlarını değiştirir.

In [71]:
# Check values of Y, reshape Y and tranposed Y
print("Normal Y:")
print(Y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


# Genel olraak matrix çarpımı yaparken transpoze işleminini kulanacağız

# Chanching the datatype of a tensor

In [72]:
# Create a new tensor with default datatype(float32)
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [73]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [74]:
# Change from float32 to float16 (reduce precision)
D=tf.cast(B,dtype=tf.float16)
D,B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float32)

In [75]:
# Change from int32 to float32
E = tf.cast(C,dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [76]:
E_float16 = tf.cast(E,dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

In [77]:
D=tf.constant([[1,2,3],
               [4,5,6]])
D.dtype

tf.int32

In [78]:
D=tf.cast(D,dtype=tf.int16)
D.dtype

tf.int16

#### Aggregating tensors 

In [79]:
# Get absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [80]:
# Get the absulute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:

* Get the minumum

* Get the maximum

* Get the mean of a tensor

- Get the sum of tensor

In [81]:
import numpy as np

In [82]:
# Create a random tensor with values between 0 and 100 of size 50
E= tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([71, 47, 78, 92,  5, 22, 94, 62,  8, 61, 67, 99, 98, 38, 43, 86, 85,
       15, 24, 30, 39, 92, 12, 25,  3, 79, 75,  4, 56, 12,  1, 78, 30,  7,
       34, 81, 89, 61,  2,  4, 86, 83, 34, 11, 65,  4, 97, 67, 15, 22])>

In [83]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [84]:
# Find the minumum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [85]:
np.min(E)

1

In [86]:
# find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [87]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [88]:
# Find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2393>

**Exercise:** find the variance and standart deviation of our E tensor using TensorFlow methods

In [89]:
C=tf.constant(np.random.randint(0,100,size=60))
C

<tf.Tensor: shape=(60,), dtype=int64, numpy=
array([49, 76, 32, 92, 95, 82, 70, 62, 91,  2, 94, 69, 64, 99, 42, 21,  7,
       22, 39, 61, 70, 20,  7, 22, 64, 78, 17, 15, 18, 24, 73, 82, 55, 85,
       30, 93, 82, 12, 64, 94, 51,  2, 67,  1, 57,  2, 59, 98, 62, 22, 82,
       67, 29,  8, 72,  0, 89, 42,  8, 30])>

In [90]:
# Find the variance of our tensor
tf.reduce_variance(E)# won't work ...

AttributeError: ignored

In [91]:
# To find the variance of our tensor , we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1090>

In [92]:
# Find the standart deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=33.03>

In [93]:
# Find the variance of our E tensor
tf.math.reduce_variance(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=1091.0>

### Find the positionel maximum and minumum



In [94]:
# Create a new tensor for finding positional minimum and maxmimum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [95]:
# find the positionel maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [96]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [97]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [98]:
# check for equality
F[tf.argmax(F)] ==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [99]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [100]:
# Find the minimum using the positionel minimum index 
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [101]:
# Exercise

In [102]:
tf.random.set_seed(42)
X=tf.random.uniform(shape=[30])
X

<tf.Tensor: shape=(30,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173],
      dtype=float32)>

In [103]:
tf.argmax(X)

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [104]:
X[tf.argmax(X)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.8996835>

In [105]:
tf.argmin(X)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [106]:
X[tf.argmin(X)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [107]:
# Create a tensor to get started
tf. random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [108]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [111]:
G_squeezed=tf.squeeze(G)# tensorumuz çok fazla tek boyuta sahispe ve silmek istersek squeeze methodunu kulanabiliriz
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [113]:
# Create a list of indices
some_list=[0,1,2,3]# could be red,green,blue,purple
# One hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [117]:
# Specify custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value='yo I love deep learning',off_value='I also like to dance') # 0 değerine karşılık gelen yo I love dep learning 0 değerine karşılık gelen ise I also like to dance değeridir

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [116]:
some_list1=[0,1,2,3,4,5,6,7,8,9]
tf.one_hot(some_list1,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

### Squaring,log,square root

In [119]:
# Create a new tensor
H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [120]:
# Square it(Kare alma fonksiyonu)
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [125]:
# find the squareroot (will eror,method,requires non-int type)
tf.sqrt(H)

InvalidArgumentError: ignored

In [123]:
#  Find the squareroot
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [128]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float32))# veri tipi int 32 olduğu için hata veriyor veri tipini floata çevirmemiz lazım

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensor ve Numpy Güzel bir şekilde etkileşime girer

In [129]:
# Create a tensors directly from a NumPy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [130]:
# Convert our tensors back to a Numpy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [131]:
# convert tensor J to Numpy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [134]:
 J=tf.constant([3.])
 J.numpy()[0]

3.0

In [135]:
# The deafult types of each are slightly different
numy_j=tf.constant(np.array([3.,7.,10.]))
tensor_j=tf.constant([3.,7.,10])
# check the datatypes of each
numy_j.dtype,tensor_j.dtype
# Numpy kulanarak bir tensor yaratmak ile tensor ile yaratmak arsındaki veri tipi farkı olabilir

(tf.float64, tf.float32)

#### Finding access to GPUs

In [2]:
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

GPU (Graphics Processing Unit - Grafik İşlem Birimi), bilgisayarların grafik işlemlerini hızlandırmak için kullanılan bir donanım bileşenidir. GPU'lar, özellikle oyunlar ve video işleme gibi yoğun grafik gerektiren uygulamalarda yüksek performans sağlarlar. Ayrıca, yapay zeka ve derin öğrenme gibi yoğun hesaplama gerektiren işlemlerde de kullanılabilirler.

TPU (Tensor Processing Unit - Tensor İşlem Birimi), Google tarafından geliştirilmiş bir özel işlem birimidir. TPU'lar, yapay zeka ve derin öğrenme gibi büyük ölçekli veri işleme işlerinde özel olarak tasarlanmıştır. TPU'lar, özellikle Google'ın yapay zeka ve makine öğrenmesi platformu olan TensorFlow ile kullanıldığında yüksek performanslı hesaplama yapabilmektedirler. TPU'lar, büyük ölçekli veri işleme işleri için özellikle yüksek performans sağlar ve CPU ve GPU'lardan daha yüksek bir performans sunarlar.

In [3]:
!nvidia-smi

Sun Apr 16 11:44:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8    11W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------